### ISSUE TITLE
[#133: USER STORY] Add Voting Feature To Q/A

### ISSUE THREAD

**Issue by njayem** [leoenix/soen-341#133]
# User Story :curly_haired_man:

**As a** *`Registered User`*, **I want to** *`be able to upvote or downvote a question, answer, or comment I deem reasonable`* **so that** *`I can help other users find reliable answers by providing feedback`*.

## Total Story Points
[16] Points

## Priority Level:
Urgent

## Risk
(High Value, High RIsk)

## Acceptance Criterion / Tasks To Be Completed _(Ordered based on priority)_ :white_check_mark:

- [X] Task #123 - Assignee (Nadine @njayem)
- [X] Task #124 - Assignees (Nadine @njayem and Eric @leoenix)
- [X] Task #126 - Assignees (Nadine @njayem and Eric @leoenix)
