### ISSUE TITLE
[#135: USER STORY] Select The Best Answer

### ISSUE THREAD

**Issue by njayem** [leoenix/soen-341#135]
# User Story :curly_haired_man:

**As a** *`Registered User`*, **I want to** *`be able to select the best answer to my question`* **so that I can** *`help others spot reliable answers as well as to thank the answer owner for their efforts publicly`*.

## Total Story Points
[9] Points

## Priority Level:
Urgent

## Risk
(High Value, High RIsk)

## Acceptance Criterion / Tasks To Be Completed _(Ordered based on priority)_ :white_check_mark:
- [X] Task #179 - Assignee (Eric @leoenix)
- [X] Task #180 - Assignee (Eric @leoenix)
- [X] Task #181 - Assignee (Eric @leoenix)
