### ISSUE TITLE
[#173: USER STORY] Add Comment Sections Under Q/A

### ISSUE THREAD

**Issue by njayem** [leoenix/soen-341#173]
# User Story :curly_haired_man:

**As a** *`Logged-In User`*, **I want to** *`be able to engage with other users by leaving comments on their questions and answers `* **so that I can** *`start a conversation with them and help them find a solution`*.

## Total Story Points
[10] Points

## Priority Level:
Urgent
## Risk
(High Value, Low Risk)

## Acceptance Criterion / Tasks To Be Completed _(Ordered based on priority)_ :white_check_mark:
- [X] Task #127   - Assignee (Eric @leoenix)
- [X] Task #128  - Assignee (Eric @leoenix)
- [X] Task #171  - Assignee (Eric @leoenix)
