### ISSUE TITLE
[#185: FEATURE] Write Acceptance Tests

### ISSUE THREAD

**Issue by njayem** [leoenix/soen-341#185]
# **Feature Request** :electron: 

## **Is your feature request / task related to a problem? Please describe.** <br>
No illustration of the behavior of the system's user stories.<br>

## **Describe the solution you'd like** <br>
Add Acceptance Testing for every User Story. An Acceptance Test is a formal description of the behavior of a software product, generally expressed as an example or a usage scenario. <br>

Write an Acceptance Test for each of the following User Stories:
- [X] #44 - Assignee (Safaa @safaaraed99)
- [X] #41 - Assignee (Safaa @safaaraed99)
- [X] #46 - Assignee (Arandeep @Arandeep24)
- [X] #48 - Assignee (Arandeep @Arandeep24)
- [X] #133 - Assignee (Raja @rajachandi)
- [X] #135 - Assignee (Raja @rajachandi)
- [X] #172 - Assignee (Warda @wardasalem)
- [X] #173 - Assignee (Warda @wardasalem)

## Total Story Points 
[4] Points
