### ISSUE TITLE
[#41: USER STORY] Log In / Log Out

### ISSUE THREAD

**Issue by leoenix** [leoenix/soen-341#41]
# User Story :curly_haired_man:

**As a** *`registered user`*, **I want to** *`log in and log out with my created account`* **so that I can** *`have access to the features of the project and my information as well as be able to end my user session at any time`*.

## Total Story Points 
[8] Points

## Acceptance Criterion / Tasks To Be Completed :white_check_mark:
- [X] Task #83 - Assignee (Michael @narroarrow)
- [X] Task #84 - Assignee (Michael @narroarrow)
- [X] Task #136 - Assignee (Michael @narroarrow)
- [X] Task #137 - Assignee (Michael @narroarrow)
- [X] Task #138 - Assignee (Michael @narroarrow)
- [X] Task #139 - Assignee (Eric @leoenix)
- [X] Task #140 - Assignee (Eric @leoenix)
- [X] Task #141 - Assignee (Eric @leoenix)
