### ISSUE TITLE
[#44: USER STORY] Account Creation

### ISSUE THREAD

**Issue by leoenix** [leoenix/soen-341#44]
# User Story :curly_haired_man:

**As a** *`regular user`*, **I want to** *`be able to create a new account`* **so that I can** *`log in to the website and have a my account page containing all my information`*.

## Total Story Points 
[8] Points

## Acceptance Criterion / Tasks To Be Completed :white_check_mark:
- [X] Task #142 - Assignee (Eric @leoenix)
- [X] Task #143 - Assignee (Eric @leoenix)
- [X] Task #144 - Assignee (Eric @leoenix)
- [X] Task #146 - Assignee (Eric @leoenix)

## Basic Flow (ends in success):
1) 
2)
3)
4) add more steps as needed
