### ISSUE TITLE
[#46: USER STORY] Ask Questions On The Forum

### ISSUE THREAD

**Issue by leoenix** [leoenix/soen-341#46]
# User Story :curly_haired_man:

**As a** *`Registered User`*, **I want to** *`be able to create a new question`* **so that I can** *`get an answer to my question`*.

## Total Story Points 
[16] Points

## Priority Level:
Urgent

## Risk
(High Value, High Risk)

## Acceptance Criterion / Tasks To Be Completed :white_check_mark:
- [X] Task #114 - Assignee (@njayem)
- [X] Task #115 - Assignee (@njayem)
- [X] Task #116 - Assignee (@njayem)
- [X] Task #85 - Assignee (@njayem)
- [X] Task #154 - Assignee (Eric @leoenix)
- [X] Task #89 - Assignee (Eric @leoenix)
- [X] Task #76 - Assignee (Eric @leoenix)
- [X] Task #169 - Assignee (Eric @leoenix)
- [X] Task #117  - Assignee (Eric @leoenix)
- [X] Task #122 - Assignee (Eric @leoenix)
